### PR TITLE
Implemented non-tradable API and UI changes(needs testing)

### LINKED ISSUE #20: Build out system for badges
Badges are non-craftable, non-tradable items that people can be granted to players for accomplishing certain tasks. Things we need to get this:

- [x] logic in Core for non-tradeable items
- [x] frontend for badge granters to grant badges to people

### PR DESCRIPTION
**Pull request by Bee4Queer**
Fixes #20.
Can someone who has experience testing bag (or is willing to pull their hair out) test it please?

### CODE REVIEW

**Comment by rivques** [comment]
Have you tested this yourself and are asking for a second opinion, or is this entirely untested?

If the second, you should get bag running locally and test it yourself (ask jc for help if needed). This won't be the only time you'll need it.

If the first, I'll get bag running locally this weekend and take a look.

**Comment by Bee4Queer** [comment]
> Have you tested this yourself and are asking for a second opinion, or is this entirely untested?
> 
> If the second, you should get bag running locally and test it yourself (ask jc for help if needed). This won't be the only time you'll need it.
> 
> If the first, I'll get bag running locally this weekend and take a look.

It's the second but over the weekend i'll get it running. I just also need to get the bag-manifest repo up so I can actually have items, then i need to use the bot to manually get both a tradable and untradable item and test both with another person so i also need to give THEM both

Although I did just realize I need to make it so you also can't give untradable items away.

**Comment by Bee4Queer** [comment]
Ok this *should* work and Manitej needs non-tradables implemented and if it breaks in production(which it shouldn't) we can revert the commit

**Comment by rivques** [comment]
I want to push #26 before this one, but  once that happens (and that should happen soon) then this looks good

**Comment by rivques** [comment]
I'm going to merge this into a side branch, and if that works I'll push it to prod.

**Pull request merged**
